# Logging configuration (toml 0.5.1)
scroll-lock = false
soft-wrap = false

[format]
show-level = true
show-logger = true
show-thread = true
show-time = true

[[loggers]]
level = 2
name = 'misc'

[[loggers]]
level = 4
name = 'testing'

[[loggers]]
level = 1
name = 'main'
